// Barrel re-export — the canonical module lives in lib/.
export {
  type PublishConfigIdentity,
  type PublishConfigKey,
  type PublishConfigKeyKind,
  type PublishConfigRenderId,
  type PublishSelectionIdentity,
  createPresetConfigKey,
  createProjectProfileConfigKey,
  createProjectProfileSelectedPreset,
  createRecentConfigRenderId,
  createUserProfileConfigKey,
  getActiveProfileNameFromSelection,
  getProjectProfileNameFromConfigKey,
  getProjectProfileNameFromRenderId,
  getProjectProfileNameFromSelection,
  getRecentConfigKeyFromRenderId,
  getRecentConfigKeyFromSelection,
  getSelectedProjectProfileName,
  getUserProfileNameFromConfigKey,
  getUserProfileNameFromRenderId,
  normalizeRenderableConfigId,
  parsePublishConfigKey,
  resolveDotnetRecentConfigKeyForSelection,
  resolvePublishSelectionIdentity,
  resolveSelectedPublishConfigKey,
  resolveSelectedPublishConfigKeyFromIdentity,
} from "@/lib/publishConfigIdentity";
