use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use ts_rs::TS;

const GENERATED_CONTRACT_HEADER: &str =
    "// This file is generated by src-tauri/examples/generate_tauri_contracts.rs.\n// Do not edit this file directly.\n";
const JSON_VALUE_DECLARATION: &str =
    "export type JsonValue = null | boolean | number | string | Array<JsonValue> | { [key: string]: JsonValue };\n";

fn push_contract<T: TS + 'static>(declarations: &mut Vec<String>) {
    declarations.push(format!("export {}", T::decl()));
}

pub fn generate_tauri_contracts() -> String {
    let mut declarations = Vec::new();

    push_contract::<crate::artifact::PackageFormat>(&mut declarations);
    push_contract::<crate::artifact::PackageResult>(&mut declarations);
    push_contract::<crate::artifact::SignMethod>(&mut declarations);
    push_contract::<crate::artifact::SignResult>(&mut declarations);
    push_contract::<crate::commands::ProjectInfo>(&mut declarations);
    push_contract::<crate::commands::ProjectPublishProfileFile>(&mut declarations);
    push_contract::<crate::commands::PublishLogChunkEvent>(&mut declarations);
    push_contract::<crate::commands::ProtectedDirectoryLocation>(&mut declarations);
    push_contract::<crate::commands::PublishOutputValidationStatus>(&mut declarations);
    push_contract::<crate::commands::PublishOutputValidationIssue>(&mut declarations);
    push_contract::<crate::commands::PublishOutputValidation>(&mut declarations);
    push_contract::<crate::commands::PublishOutputAccessStatus>(&mut declarations);
    push_contract::<crate::commands::PublishOutputAccess>(&mut declarations);
    push_contract::<crate::commands::PublishOutputPreflightResult>(&mut declarations);
    push_contract::<crate::commands::PublishResult>(&mut declarations);
    push_contract::<crate::commands::ProjectScanCandidates>(&mut declarations);
    push_contract::<crate::commands::RepositoryBranchConnectivityResult>(&mut declarations);
    push_contract::<crate::commands::RepositoryBranchScanResult>(&mut declarations);
    push_contract::<crate::commands::UpdateDownloadProgressPayload>(&mut declarations);
    push_contract::<crate::commands::UpdateInfo>(&mut declarations);
    push_contract::<crate::commands::UpdaterConfigHealth>(&mut declarations);
    push_contract::<crate::commands::UpdaterHelpPaths>(&mut declarations);
    push_contract::<crate::config_export::ConfigExport>(&mut declarations);
    push_contract::<crate::config_export::ConfigProfile>(&mut declarations);
    push_contract::<crate::environment::EnvironmentCheckResult>(&mut declarations);
    push_contract::<crate::environment::EnvironmentIssue>(&mut declarations);
    push_contract::<crate::environment::FixAction>(&mut declarations);
    push_contract::<crate::environment::FixResult>(&mut declarations);
    push_contract::<crate::environment::FixType>(&mut declarations);
    push_contract::<crate::environment::IssueSeverity>(&mut declarations);
    push_contract::<crate::environment::IssueType>(&mut declarations);
    push_contract::<crate::environment::ProviderStatus>(&mut declarations);
    push_contract::<crate::parameter::ParameterDefinition>(&mut declarations);
    push_contract::<crate::parameter::ParameterSchema>(&mut declarations);
    push_contract::<crate::parameter::ParameterType>(&mut declarations);
    push_contract::<crate::provider::ProviderManifest>(&mut declarations);
    push_contract::<crate::shortcuts::ShortcutHelp>(&mut declarations);
    push_contract::<crate::spec::PublishSpec>(&mut declarations);
    push_contract::<crate::spec::SpecValue>(&mut declarations);
    push_contract::<crate::store::AppState>(&mut declarations);
    push_contract::<crate::store::Branch>(&mut declarations);
    push_contract::<crate::store::ConfigProfile>(&mut declarations);
    push_contract::<crate::store::ExecutionRecord>(&mut declarations);
    push_contract::<crate::store::PublishConfigStore>(&mut declarations);
    push_contract::<crate::store::RepoPublishConfig>(&mut declarations);
    push_contract::<crate::store::Repository>(&mut declarations);

    let mut content = String::from(GENERATED_CONTRACT_HEADER);
    content.push('\n');
    content.push_str(JSON_VALUE_DECLARATION);
    content.push('\n');
    content.push_str(&declarations.join("\n\n"));
    content.push('\n');
    content
}

pub fn generated_contract_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("src-tauri should have a workspace root")
        .join("src/generated/tauri-contracts.ts")
}

pub fn write_generated_tauri_contracts(output_path: &Path) -> io::Result<()> {
    let content = generate_tauri_contracts();
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(output_path, content)
}

#[cfg(test)]
mod tests {
    use super::{generate_tauri_contracts, generated_contract_path};

    #[test]
    fn generated_tauri_contracts_match_committed_file() {
        let expected = generate_tauri_contracts();
        let output_path = generated_contract_path();
        let actual = std::fs::read_to_string(&output_path).unwrap_or_else(|error| {
            panic!(
                "读取生成合同失败 ({}): {}。请运行 `cargo run --manifest-path src-tauri/Cargo.toml --example generate_tauri_contracts`。",
                output_path.display(),
                error
            )
        });

        assert_eq!(
            actual, expected,
            "Tauri 共享合同已漂移。请运行 `cargo run --manifest-path src-tauri/Cargo.toml --example generate_tauri_contracts` 更新 {}。",
            output_path.display()
        );
    }
}
